# Generated by Django 4.2.4 on 2023-08-30 16:41

import ckeditor_uploader.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContestRound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_label', models.CharField(max_length=250)),
                ('round_duration', models.DurationField()),
            ],
        ),
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problem_name', models.CharField(max_length=600)),
                ('content', ckeditor_uploader.fields.RichTextUploadingField()),
                ('contest_round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='problems', to='contest_round.contestround')),
            ],
        ),
        migrations.CreateModel(
            name='UserResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.TextField()),
                ('contest_round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contest_round.contestround')),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contest_round.problem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
