# Generated by Django 4.2.4 on 2023-09-03 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest_round', '0003_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='contestround',
            name='has_started',
            field=models.BooleanField(default=False),
        ),
    ]
