# Generated by Django 4.2.4 on 2023-09-04 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest_round', '0004_contestround_has_started'),
    ]

    operations = [
        migrations.AddField(
            model_name='userresponse',
            name='has_solved',
            field=models.BooleanField(default=False),
        ),
    ]
