# Generated by Django 4.2.4 on 2023-09-04 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest_round', '0005_userresponse_has_solved'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportedlanguage',
            name='judge0_id',
            field=models.IntegerField(default=71),
        ),
    ]
