# Generated by Django 4.2.4 on 2023-09-12 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest_round', '0006_supportedlanguage_judge0_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='userresponse',
            name='submission_time',
            field=models.TimeField(null=True),
        ),
    ]
