# Generated by Django 4.2.4 on 2023-09-12 04:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contest_round', '0007_userresponse_submission_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserResponsePoints',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marks', models.IntegerField()),
                ('user_response', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contest_round.userresponse')),
            ],
        ),
    ]
