# Generated by Django 4.2.4 on 2023-09-26 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest_round', '0010_homepagecontent'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='userresponse',
            constraint=models.UniqueConstraint(fields=('user', 'problem'), name='unique_user_response'),
        ),
    ]
