# Generated by Django 4.2.4 on 2023-10-04 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest_round', '0013_userfoul'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='foul_count',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='Userfoul',
        ),
    ]
