# Generated by Django 4.2.4 on 2023-10-04 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest_round', '0014_userprofile_foul_count_delete_userfoul'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userresponse',
            name='submission_time',
            field=models.TimeField(),
        ),
    ]
