version: "3.8"

services:
  web:
    build: ./contest_website  # Update the path to your Django project directory
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./contest_website:/usr/src/app/  # Update the path to your Django project directory
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=hello_django
      - POSTGRES_PASSWORD=hello_django
      - POSTGRES_DB=hello_django_dev

volumes:
  postgres_data:
