version: '3.8'

services:
  web:
    build:
      context: ./contest_website
      dockerfile: Dockerfile.prod
    command: gunicorn contest_website.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/home/contest_website/web/staticfiles
      - media_volume:/home/contest_website/web/media
    expose:
      - 8000
    env_file:
      - ./.env.prod
    depends_on:
      - db_django
    networks:
      - contest_network  # Assigning the 'contest_network' to the 'web' service
    restart: always
    
  db_django:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.prod.db
    networks:
      - contest_network  # Assigning the 'contest_network' to the 'nginx' service
    restart: always

  nginx:
    build: ./nginx
    volumes:
      - static_volume:/home/contest_website/web/staticfiles
      - media_volume:/home/contest_website/web/media
    ports:
      - 1337:80
    depends_on:
      - web
    networks:
      - contest_network  # Assigning the 'contest_network' to the 'nginx' service
    restart: always
    
volumes:
  postgres_data:
  static_volume:
  media_volume:

networks:
  contest_network:
    external: true  # This network is external
