# pull official base image
FROM python:3.11.4-slim-buster

# set work directory
WORKDIR /usr/src/contest_website

# set environment variables
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

# install dependencies
RUN pip install --upgrade pip
COPY ./requirements.txt .
RUN pip install -r requirements.txt

# Install nc (netcat)
RUN apt-get update && apt-get install -y netcat

# copy project
COPY . ./

# run entrypoint.sh
ENTRYPOINT ["/usr/src/contest_website/entrypoint.sh"]

